Add support for GITHUB_OUTPUT and GITHUB_ENV

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -48,3 +48,33 @@ jobs:
       shell: run_in_container.sh --shell sh {0}
       run: |
         echo "Arch in container: $(uname -m)"
+    - name: Set output and env from outside container
+      shell: bash
+      id: set_outside
+      run: |
+        echo "value=I_AM_OUTSIDE" >> $GITHUB_OUTPUT
+        echo "OUTSIDE_VAR=ENV_OUTSIDE" >> $GITHUB_ENV
+    - name: Set output and env from inside container
+      shell: run_in_container.sh {0}
+      id: set_inside
+      run: |
+        echo "value=I_AM_INSIDE" >> $GITHUB_OUTPUT
+        echo "INSIDE_VAR=ENV_INSIDE" >> $GITHUB_ENV
+    - name: Check output and env from outside container
+      shell: bash
+      run: |
+        RVAL=0
+        [[ "${OUTSIDE_VAR}" != "ENV_OUTSIDE" ]] && echo "Error: OUTSIDE_VAR check failed: $OUTSIDE_VAR" && RVAL=1
+        [[ "${INSIDE_VAR}" != "ENV_INSIDE" ]] && echo "Error: INSIDE_VAR check failed: $INSIDE_VAR" && RVAL=1
+        [[ "${{ steps.set_outside.outputs.value }}" != "I_AM_OUTSIDE" ]] && echo "Error: outside output check failed: ${{ steps.set_outside.outputs.value }}" && RVAL=1
+        [[ "${{ steps.set_inside.outputs.value }}" != "I_AM_INSIDE" ]] && echo "Error: inside output check failed: ${{ steps.set_inside.outputs.value }}" && RVAL=1
+        exit $RVAL
+    - name: Check output and env from inside container
+      shell: bash
+      run: |
+        RVAL=0
+        [[ "${OUTSIDE_VAR}" != "ENV_OUTSIDE" ]] && echo "Error: OUTSIDE_VAR check failed: $OUTSIDE_VAR" && RVAL=1
+        [[ "${INSIDE_VAR}" != "ENV_INSIDE" ]] && echo "Error: INSIDE_VAR check failed: $INSIDE_VAR" && RVAL=1
+        [[ "${{ steps.set_outside.outputs.value }}" != "I_AM_OUTSIDE" ]] && echo "Error: outside output check failed: ${{ steps.set_outside.outputs.value }}" && RVAL=1
+        [[ "${{ steps.set_inside.outputs.value }}" != "I_AM_INSIDE" ]] && echo "Error: inside output check failed: ${{ steps.set_inside.outputs.value }}" && RVAL=1
+        exit $RVAL
